### PR TITLE
New domain register

### PR DESCRIPTION
**Pull request by santydesignscr**
Registered with register.bytewave.wip.la, try it!

### CODE REVIEW

**Comment by pepa65** [comment]
Actually, with test.bytewave.wip.la as I cannot resolve register.bytewave.wip.la here...

**Comment by santydesignscr** [comment]
register.bytewave.wip.la don't exist, sorry I will update it

**Comment by santydesignscr** [comment]
And your domain is ready, as you see it was merged

**Comment by pepa65** [comment]
Thanks @santydesignscr you have made a very nice service for this project!

**Comment by santydesignscr** [comment]
I only do it by returning, since the domain was very useful to me too. I already connected the creator to create a better website and to directly manage the domain and thus replace the repository, since this website that I made takes 30s to add a domain and if while one is registered they try to register another, there are problems, this current version that interacts with the repository is giving many technical limitations.

**Comment by santydesignscr** [comment]
If you want you can take a look at my main website and if you share it it would help me a lot https://bytewave.wip.la

**Pull request merged**
