### PR TITLE
Update earth.cluster.ws Name Servers

### PR DESCRIPTION
**Pull request by ArtieFuzzz**

### CODE REVIEW

**Comment by ArtieFuzzz** [comment]
I'll just close this for good

**Comment by politician** [comment]
@ArtieFuzzz https://github.com/Olivr/free-domain/issues/30

**Comment by ArtieFuzzz** [comment]
Ah, I see

**Comment by politician** [comment]
I can make the modification if you want?

**Comment by ArtieFuzzz** [comment]
I've changed my mind and I don't really want to change the name servers anymore

**Comment by politician** [comment]
@ArtieFuzzz ok done

**Pull request merged**
