### PR TITLE
Update cluster.ws.yaml

### PR DESCRIPTION
**Pull request by ItzArman09**

### CODE REVIEW

**Comment by ItzArman09** [comment]
even if i dont edit other things, it shows as i edited and readded it :(

**Comment by ArtieFuzzz** [comment]
Auto-merging for domain modifications are currently off (see #30)

And also please register only one domain per PR

**Comment by ItzArman09** [comment]
I added only 1 domain

**Comment by politician** [comment]
@ItzArman09 Look at the changes: https://github.com/Olivr/free-domain/pull/134/files

Your editor is probably doing some formatting, try to use vim, nano, notepad, etc.

**Pull request closed without merging**
