### PR TITLE
Update balloon.wip.la

### PR DESCRIPTION
**Pull request by fu-sen**
When I updated the zone, it seems that the automatic update process is currently pending. I'm hoping for that improvement and I'll add it to the pull request queue.

### CODE REVIEW

**Comment by politician** [comment]
@fu-sen do you still want this changed? I can merge it manually if you wish.

**Comment by fu-sen** [comment]
I would like to change my DNS. Luckily I got dns.he.net to work, but I don't think it usually works with subdomains. Ideally it should be set in ClouDNS for others to see.

**Comment by fu-sen** [comment]
ClouDNS had just deleted the zone because there was no nameserver lookup for a month. I have reconfigured. You can always change it manually.

**Comment by politician** [comment]
Can you rebase your branch off the latest main and push again? I'll then be able to merge.

**Comment by fu-sen** [comment]
According to GitHub specs, when I delete a forked project that has patched a pull request, the pull request will be closed.
A replacement pull request has been inherited: https://github.com/Olivr/free-domain/pull/280

**Pull request closed without merging**
